name: pyramakerz_task_f
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  mqtt_client: ^10.5.1
  speech_to_text: ^7.0.0
  tflite:
    git:
      url: https://github.com/sumn2u/flutter_tflite.git
      ref: main


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/



