name: pyramakerz_task_f
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  camera: ^0.11.0+2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  image: ^4.3.0
  image_picker: ^1.1.2
  speech_to_text: ^7.0.0
  tflite: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/mobilenet_v1_1.0_224.tflite
    - assets/mobilenet_v1_1.0_224.txt


